### ISSUE TITLE
Chromium Does Not Support VPU HW Acceleration and No WiFI with RTL8852BE-CG Module

### ISSUE THREAD

**Issue by JFLim1** [armsurvivors/armbian-release#2]
Thank for building https://github.com/armsurvivors/armbian-release/releases/download/24.04.01-armsurvivors-78/Armbian-unofficial_24.04.01-armsurvivors-78_Orangepi5-plus_jammy_vendor-boogie-panthor_6.1.43_kde-neon-amazingfated-oibaf_desktop.img.xz.

Flash onto an SD Card and boot up successfully on Opi5-Plus.  Performed the usual "sudo apt update && sudo apt upgrade".  After first system upgrade launch Chromium and noticed there is NO vpu hw acceleration.  Check that "libv4l-rkmpp" was NOT installed so proceed to install "libv4l-rkmpp".  Reboot and launch Chromium again.  chrome://gpu indicate that vpu hw acceleration is available.

![image](https://github.com/armsurvivors/armbian-release/assets/75384411/d609503a-9060-41c1-b798-a67ba49f64f2)

But when stream a 4K Youtube video and will notice there is NO vpu hw acceleration available.  High CPU usage according to HTOP and error messages:

```
Failed to query video capabilities: Inappropriate ioctl for device
Failed to query video capabilities: Inappropriate ioctl for device
[0403/214302.620417:ERROR:process_memory_linux.cc(49)] pread64: Input/output error (5)
Received signal 11 SEGV_MAPERR 000000000032
#0 0xaaaaee5e6c38 (/usr/lib/chromium-browser/chromium-browser+0x50c6c37)
#1 0xaaaaee5d5280 (/usr/lib/chromium-browser/chromium-browser+0x50b527f)
#2 0xaaaaee5e6b50 (/usr/lib/chromium-browser/chromium-browser+0x50c6b4f)
#3 0xffffa33307b0 ([vdso]+0x7af)
#4 0xffffa1c67c18 (/usr/lib/aarch64-linux-gnu/libc.so.6+0x97c17)
#5 0xaaaaec6fd94c (/usr/lib/chromium-browser/chromium-browser+0x31dd94b)
#6 0xaaaaec6fd9e0 (/usr/lib/chromium-browser/chromium-browser+0x31dd9df)
#7 0xaaaaec6fd16c (/usr/lib/chromium-browser/chromium-browser+0x31dd16b)
#8 0xaaaaec6f8b84 (/usr/lib/chromium-browser/chromium-browser+0x31d8b83)
#9 0xaaaaec705eb4 (/usr/lib/chromium-browser/chromium-browser+0x31e5eb3)
#10 0xaaaaee58c3d8 (/usr/lib/chromium-browser/chromium-browser+0x506c3d7)
#11 0xaaaaee5a3f20 (/usr/lib/chromium-browser/chromium-browser+0x5083f1f)
#12 0xaaaaee5a3ad8 (/usr/lib/chromium-browser/chromium-browser+0x5083ad7)
#13 0xaaaaee548360 (/usr/lib/chromium-browser/chromium-browser+0x502835f)
#14 0xaaaaee5a45b4 (/usr/lib/chromium-browser/chromium-browser+0x50845b3)
#15 0xaaaaee56c268 (/usr/lib/chromium-browser/chromium-browser+0x504c267)
#16 0xaaaaee5b48b0 (/usr/lib/chromium-browser/chromium-browser+0x50948af)
#17 0xaaaaee5b4a10 (/usr/lib/chromium-browser/chromium-browser+0x5094a0f)
#18 0xaaaaee5c7120 (/usr/lib/chromium-browser/chromium-browser+0x50a711f)
#19 0xffffa1c4d5c8 (/usr/lib/aarch64-linux-gnu/libc.so.6+0x7d5c7)
#20 0xffffa1cb5d9c (/usr/lib/aarch64-linux-gnu/libc.so.6+0xe5d9b)
[end of stack trace]
[23477:7:0403/214302.674545:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[23399:23399:0403/214302.731902:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=11
[24018:24018:0403/214302.887457:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[24018:24018:0403/214302.887652:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[24018:24018:0403/214302.887757:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[24018:24018:0403/214302.887845:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[24018:24018:0403/214302.887927:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[24018:24018:0403/214302.888010:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[24018:24018:0403/214302.888091:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
```
And "chrome://gpu" report initially indicates as follows:
![Chromium-with-vpu-gpu-accl](https://github.com/armsurvivors/armbian-release/assets/75384411/e706e19d-b7f1-46d0-b9c1-3c6fce6646d7)

Change to:
![Chromium-No-vpu-gpu-accl](https://github.com/armsurvivors/armbian-release/assets/75384411/37f3353c-750c-41ef-912e-4fe523d82c09)

When a Youtube video is being streamed.

Is there any other package other than "libv4l-rkmpp" needed to be installed or any settings need to be set?

The panthor-kernel and panthor seems to have resolved the occasional KDE Plasmashell crash.  Another good point is Firefox now does not freeze or crash frequently anymore.  With mesa-panfork Firefox freezes and crashes quite frequently and also have visual artifacts times on webpages.

Installed mpv and mpv do stream with vpu hw acceleration.

**Comment by rpardini** [comment]
Nice, thanks for your report. I've no idea, though.
